# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            this is not the content
tagline:          ''
description:      ''
url:              http://dpadr.github.io/
baseurl:          http://dpadr.github.io/

author:
  name:           'David'
  url:

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
