# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            this is not the content
tagline:          'a'
description:      'we willingly donate to “social" platforms includes the best part of you — YOU. we’ve made those platforms precisely as valuable as they are by giving away large parts of ourselves (not to mention our data, privacy, friends and attention). this is my attempt to short circuit the wires, to present what I have to YOU, while remaining firmly divested from them. of course, this too is a cheap facsimile — this is not the content — but it’s what we’ve got.'
url:              http://dpadr.github.io
baseurl:          /

author:
  name:           'David'
  url:

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
